version: "1"
services:
- type: web
  name: voluntrack-backend
  runtime: node
  repo: https://github.com/Hriday21223/VolunteerTrack
  plan: free
  envVars:
  - key: RESEND_API_KEY
    sync: false
  - key: NODE_ENV
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: EMAIL_FROM
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: PORT
    sync: false
  region: oregon
  buildCommand: npm ci
  startCommand: node server.js
  autoDeployTrigger: commit
