import express from 'express'
import cors from 'cors'
import rateLimit from 'express-rate-limit'
import dotenv from 'dotenv'
import { Resend } from 'resend'
import { initSchema, hasDatabase, query } from './server/db.js'
import { authenticate, hashPassword } from './server/auth.js'
import { uid } from './server/ids.js'
import authRoutes from './server/routes/auth.js'
import schoolRoutes from './server/routes/school.js'

dotenv.config()

const app = express()
const port = process.env.PORT || 10000



// General rate limiting for API endpoints
const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100, // 100 requests per windowMs
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many requests. Please try again later.' },
})

// Stricter rate limiting for email endpoints
const emailLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour
  max: 20, // 20 emails per hour
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: 'Too many email requests. Please try again later.' },
})

app.set('trust proxy', 1)
app.use(cors())
app.use(express.json({ limit: '1mb' })) // Limit request body size
app.use(apiLimiter)
app.use(authenticate)

// Server-backed accounts & (later) school dashboards.
app.use('/api/auth', apiLimiter, authRoutes)
app.use('/api/school', apiLimiter, schoolRoutes)

// In-memory ring buffer of the most recently generated recovery codes. In
// production these are also emailed to the user; the buffer allows the
// password-reset endpoint to verify the code when the user submits it from
// the same browser (where it was already stored in localStorage).
const isProd = process.env.NODE_ENV === 'production'
const devCodeLog = []
const DEV_LOG_LIMIT = 25

function logDevCode(entry) {
  devCodeLog.unshift(entry)
  if (devCodeLog.length > DEV_LOG_LIMIT) devCodeLog.length = DEV_LOG_LIMIT
}

function transporter() {
  const apiKey = process.env.RESEND_API_KEY
  const from = process.env.EMAIL_FROM || 'onboarding@resend.dev'

  if (!apiKey) {
    return { resend: null, missing: ['RESEND_API_KEY'] }
  }

  return {
    resend: new Resend(apiKey),
    from,
    missing: [],
  }
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[c]))
}


// Lightweight status endpoint so the UI can show real setup hints instead of
// a generic "not configured" message.
app.get('/api/recovery-status', (_req, res) => {
  const { resend, missing } = transporter()
  res.json({
    smtpConfigured: Boolean(resend),
    missingVars: missing,
    devMode: !isProd,
    devCodeCount: devCodeLog.length,
  })
})

// Verify a recovery code and update the password in the database. The code
// was previously generated by the frontend, stored in localStorage, and sent
// via email. This endpoint lets the same browser complete the reset without
// waiting for the email to arrive.
app.post('/api/auth/reset-password', emailLimiter, async (req, res) => {
  const { email, code, newPassword } = req.body

  if (!email || typeof email !== 'string' || !email.includes('@') || email.length > 254) {
    return res.status(400).json({ error: 'Invalid email.' })
  }
  if (!code || typeof code !== 'string' || code.length > 20) {
    return res.status(400).json({ error: 'Invalid code.' })
  }
  if (!newPassword || typeof newPassword !== 'string' || newPassword.length < 8 || newPassword.length > 128) {
    return res.status(400).json({ error: 'Password must be at least 8 characters.' })
  }

  if (!hasDatabase()) {
    return res.status(503).json({ error: 'Server database is not configured.' })
  }

  try {
    const { rows } = await query('SELECT * FROM users WHERE email = $1', [email.trim().toLowerCase()])
    if (rows.length === 0) {
      return res.status(404).json({ error: 'No account with that email.' })
    }

    // Try to match the code from the ring buffer.
    const trimmedEmail = email.trim().toLowerCase()
    const match = devCodeLog.find(
      (entry) => entry.email.toLowerCase() === trimmedEmail && entry.code === code && entry.type === 'password'
    )
    if (!match) {
      return res.status(401).json({ error: 'Invalid or expired recovery code.' })
    }

    const hash = await hashPassword(newPassword)
    await query('UPDATE users SET password_hash = $1 WHERE id = $2', [hash, rows[0].id])

    return res.json({ ok: true })
  } catch (error) {
    console.error('reset-password failed:', error)
    return res.status(500).json({ error: 'Could not reset password.' })
  }
})

app.post('/api/send-reset-email', emailLimiter, async (req, res) => {
  const { email, code, type } = req.body
  
  // Basic input validation
  if (!email || typeof email !== 'string' || !email.includes('@') || email.length > 254) {
    return res.status(400).json({ error: 'Invalid email.' })
  }
  if (!code || typeof code !== 'string' || code.length > 20) {
    return res.status(400).json({ error: 'Invalid code.' })
  }
  if (!type || typeof type !== 'string' || (type !== 'pin' && type !== 'password')) {
    return res.status(400).json({ error: 'Invalid type.' })
  }

  const { resend, from, missing } = transporter()
  logDevCode({ email: email.trim(), code, type, at: new Date().toISOString() })

  if (!resend) {
    return res.status(503).json({
      error: 'Email backend is not configured.',
      missingVars: missing,
    })
  }

  const subject = type === 'pin'
    ? 'VolunTrack PIN recovery code'
    : 'VolunTrack password recovery code'
  const text = `Your VolunTrack recovery code is ${code}. It expires in 15 minutes.`
  const html = `<p>Your VolunTrack recovery code is <strong>${code}</strong>.</p><p>It expires in 15 minutes.</p>`

  try {
    await resend.emails.send({
      from,
      to: email,
      subject,
      text,
      html,
    })
    return res.status(200).json({ ok: true })
  } catch (error) {
    console.error('Email send failed:', error)
    return res.status(500).json({ error: 'Failed to send email.' })
  }
})

// Dev-only helper: returns the most recently generated code for an email so
// the GitHub Pages demo can deliver the code via the UI without needing SMTP.
// Returns 404 in production so a leaked URL never discloses codes.
app.get('/api/dev-recovery-code', (req, res) => {
  if (isProd) return res.status(404).json({ error: 'Not available in production.' })
  const email = String(req.query.email || '').toLowerCase().trim()
  if (!email) return res.status(400).json({ error: 'Missing email.' })
  const hit = devCodeLog.find((entry) => entry.email.toLowerCase() === email)
  if (!hit) return res.status(404).json({ error: 'No recent code for that email.' })
  return res.json({ code: hit.code, type: hit.type, at: hit.at })
})

app.post('/api/send-report', async (req, res) => {
  const { to, school, student, totalHours, entries } = req.body
  if (!to || !student) {
    return res.status(400).json({ error: 'Missing recipient or student.' })
  }

  const { resend, from, missing } = transporter()
  if (!resend) {
    return res.status(503).json({
      error: 'Email backend is not configured.',
      missingVars: missing,
    })
  }

  const rows = Array.isArray(entries) ? entries : []
  const total = typeof totalHours === 'number'
    ? totalHours
    : rows.reduce((s, e) => s + (Number(e.hours) || 0), 0)

  const textRows = rows
    .map((e) => `  ${e.date || ''}  ${e.activity || ''} (${e.category || '-'}) — ${Number(e.hours) || 0}h`)
    .join('\n')
  const text = `Volunteer report for ${student}${school ? ` (${school})` : ''}\n`
    + `Total hours: ${total}\nSessions: ${rows.length}\n\n${textRows}`

  const htmlRows = rows
    .map((e) => `<tr><td>${escapeHtml(e.date)}</td><td>${escapeHtml(e.activity)}</td>`
      + `<td>${escapeHtml(e.category)}</td><td style="text-align:right">${Number(e.hours) || 0}h</td></tr>`)
    .join('')
  const html = `
    <h2>Volunteer report for ${escapeHtml(student)}${school ? ` <small>(${escapeHtml(school)})</small>` : ''}</h2>
    <p><strong>Total hours:</strong> ${total} &nbsp;|&nbsp; <strong>Sessions:</strong> ${rows.length}</p>
    <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif;font-size:14px">
      <thead><tr><th>Date</th><th>Activity</th><th>Category</th><th>Hours</th></tr></thead>
      <tbody>${htmlRows}</tbody>
    </table>`

  try {
    await resend.emails.send({
      from,
      to,
      subject: `VolunTrack volunteer report — ${student}`,
      text,
      html,
    })
    return res.status(200).json({ ok: true })
  } catch (error) {
    console.error('Report email failed:', error)
    return res.status(500).json({ error: 'Failed to send report.' })
  }
})

app.post('/api/contact', emailLimiter, async (req, res) => {
  const { name, email, subject, message } = req.body
  
  // Basic input validation
  if (!name || typeof name !== 'string' || name.trim().length === 0 || name.length > 100) {
    return res.status(400).json({ error: 'Invalid name.' })
  }
  if (!email || typeof email !== 'string' || !email.includes('@') || email.length > 254) {
    return res.status(400).json({ error: 'Invalid email.' })
  }
  if (!message || typeof message !== 'string' || message.trim().length === 0 || message.length > 5000) {
    return res.status(400).json({ error: 'Invalid message.' })
  }
  if (subject && (typeof subject !== 'string' || subject.length > 200)) {
    return res.status(400).json({ error: 'Invalid subject.' })
  }

  const { resend, from, missing } = transporter()
  if (!resend) {
    return res.status(503).json({
      error: 'Email backend is not configured.',
      missingVars: missing,
    })
  }

  const to = process.env.CONTACT_EMAIL || 'volunteertrackinfo@gmail.com'
  const sanitizedMessage = message.trim()
  const sanitizedSubject = subject ? subject.trim() : 'General question'
  const body = `New contact message from ${name.trim()} <${email.trim()}>\nSubject: ${sanitizedSubject}\n\n${sanitizedMessage}`

  try {
    await resend.emails.send({
      from,
      to,
      reply_to: email,
      subject: `VolunTrack contact: ${subject || 'General question'}`,
      text: body,
      html: `<pre style="font-family: sans-serif; white-space: pre-wrap;">${body}</pre>`,
    })
    return res.status(200).json({ ok: true })
  } catch (error) {
    console.error('Contact email failed:', error)
    return res.status(500).json({ error: 'Failed to send message.' })
  }
})

// Root route — show available API endpoints
app.get('/', (_req, res) => {
  res.json({
    name: 'VolunTrack API',
    version: '1.0.0',
    description: 'Backend server for VolunTrack — volunteer hour tracking for students, parents, and schools.',
    endpoints: {
      auth: {
        'POST /api/auth/register': 'Create a new account (student, parent, volunteer, school, admin)',
        'POST /api/auth/login': 'Log in with email and password',
        'POST /api/auth/sync-login': 'Log in with a 5-digit sync PIN',
        'PUT /api/auth/password': 'Change account password',
        'POST /api/auth/reset-password': 'Reset password with a recovery code',
        'DELETE /api/auth/account': 'Delete your account',
        'PUT /api/auth/sync-pin': 'Set or update your 5-digit sync PIN',
        'POST /api/auth/sync-pin-auth': 'Link local account to server with sync PIN',
        'GET /api/auth/me': 'Get current user profile',
      },
      schools: {
        'POST /api/school/register': 'Register a new school',
        'POST /api/school/join': 'Join a school with its PIN code',
        'GET /api/school/info': 'Get school information',
        'GET /api/school/students': 'List students in a school (school admin)',
        'GET /api/school/students/:schoolId/pdf-status': 'Check student PDF upload status',
        'POST /api/school/upload-pdf': 'Upload a verification PDF',
        'GET /api/school/pdfs': 'List uploaded PDFs for a school',
        'PUT /api/school/pdf/:id/approve': 'Approve a PDF (school admin)',
        'PUT /api/school/pdf/:id/reject': 'Reject a PDF (school admin)',
      },
      parentLinking: {
        'POST /api/school/linking-code': 'Generate a 6-char linking code (student)',
        'POST /api/school/link-student': 'Link parent to student with code (parent)',
        'GET /api/school/linked-children': 'List linked children (parent)',
        'GET /api/school/child-hours/:studentId': 'Get child volunteer hours (parent)',
        'GET /api/school/parent-links': 'List linked parents (student)',
        'DELETE /api/school/parent-link/:linkId': 'Revoke a parent link (student)',
      },
      publicTasks: {
        'POST /api/school/public-tasks': 'Create a volunteer opportunity',
        'GET /api/school/public-tasks': 'Browse volunteer opportunities',
        'POST /api/school/public-tasks/:id/signup': 'Sign up for a task',
        'GET /api/school/public-tasks/:id/signups': 'View signups for a task',
        'PUT /api/school/public-tasks/:id/signups/:signupId': 'Approve/reject a signup',
      },
      email: {
        'POST /api/send-reset-email': 'Send a password/PIN recovery email',
        'POST /api/send-report': 'Send a volunteer report via email',
        'POST /api/contact': 'Send a contact form message',
      },
      other: {
        'GET /api/recovery-status': 'Check email server configuration',
        'GET /api/dev-recovery-code': 'Get recovery code (dev only)',
      },
    },
  })
})

// 404 handler for unknown routes
app.use((_req, res) => {
  res.status(404).json({ error: 'Not found' })
})

// Creates an admin account on boot from env so there is always a way in.
// No-op when the DB or admin env vars are missing, or the admin already exists.
async function seedAdmin() {
  const email = String(process.env.ADMIN_EMAIL || '').trim().toLowerCase()
  const password = String(process.env.ADMIN_PASSWORD || '')
  if (!hasDatabase() || !email || !password) return
  const hash = await hashPassword(password)
  const existing = await query('SELECT 1 FROM users WHERE email = $1', [email])
  if (existing.rowCount > 0) {
    await query(
      'UPDATE users SET role = $1, name = $2, password_hash = $3 WHERE email = $4',
      ['admin', 'Admin', hash, email],
    )
    console.log(`Updated admin account: ${email}`)
    return
  }
  await query(
    `INSERT INTO users (id, role, name, email, password_hash)
     VALUES ($1, 'admin', $2, $3, $4)`,
    [uid('usr'), 'Admin', email, hash],
  )
  console.log(`Seeded admin account: ${email}`)
}

async function start() {
  if (hasDatabase()) {
    try {
      await initSchema()
      await seedAdmin()
      console.log('Database ready.')
    } catch (error) {
      console.error('Database init failed:', error)
    }
  } else {
    console.log('DATABASE_URL not set — running in email-only mode (no accounts API).')
  }

  app.listen(port, () => {
    console.log(`Backend server listening at http://localhost:${port}`)
  })
}

start()
